In [1]:
import numpy as np

# Sigmoid Function
def nonlin(x, Deriv=False):
    if(Deriv):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

# Input Data Matrix
X = np.array([[0,0,1], [1,1,0], [1,0,1], [0,1,1]])

# Target Data Matrix --> To Predict
y = np.array([[0], [1], [1], [0]])

# Set Seed Value to reproduce results
np.random.random(1)

# Initialize Weights with random values
weights_l0 = np.random.random((3,1))

# Set Layer 0 as the Input data
layer_0 = X

# Set the Epochs
epochs = 50000

for iter in range(epochs):
    
    # Feed Forward through 2 Layers (Layer 0 being the I/P Layer)
    layer_1 = nonlin(np.dot(layer_0, weights_l0))                   # Layer 1 --> Activation(Last_Layer(dot)Weights)
    layer_1_error = y - layer_1                                     # Calculate Error - Prediction vs Actual Value
    layer_1_delta = layer_1_error * nonlin(layer_1, True)           # Error Weighted Derivative --> Error * Deriv(Current_Layer)
    
    weights_l0 += np.dot(layer_0.T, layer_1_delta)                  # Update the Weight Vector
    
    if (iter % 10000) == 0:
        print("Error: "+str(np.mean(np.abs(layer_1_error))))        # layer_1_error contains the Error, take the absolute Values and calculate the mean
        print("Accuracy: "+str((1 - np.mean(np.abs(layer_1_error))) * 100))
        print()
        print(layer_1)                                              # These are the Predicted Values

Error: 0.537959583787
Accuracy: 46.2040416213

[[ 0.70496194]
 [ 0.56062832]
 [ 0.72589074]
 [ 0.73339545]]
Error: 0.00641417077263
Accuracy: 99.3585829227

[[ 0.01204072]
 [ 0.99949287]
 [ 0.98987622]
 [ 0.00298505]]
Error: 0.00447526866281
Accuracy: 99.5524731337

[[ 0.00851149]
 [ 0.9997343 ]
 [ 0.99286485]
 [ 0.00198873]]
Error: 0.00363014191512
Accuracy: 99.6369858085

[[ 0.00694903]
 [ 0.99981819]
 [ 0.99418329]
 [ 0.00157302]]
Error: 0.00313070984731
Accuracy: 99.6869290153

[[ 0.00601796]
 [ 0.99986117]
 [ 0.99496747]
 [ 0.00133352]]


In [2]:
# Let's take the basic idea obtained above and build a deep(er) NN -- 2 Hidden Layers

import numpy as np

# Sigmoid Function
def nonlin(x, Deriv=False):
    if(Deriv):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

# Input Data Matrix
X = np.array([[0,0,1], [1,1,0], [1,0,1], [0,1,1]])

# Target Data Matrix --> To Predict
y = np.array([[0], [1], [1], [0]])

# Set Seed Value to reproduce results
np.random.random(1)

# Initialize Weights with random values
weights_l0 = np.random.random((3,4))
weights_l1 = np.random.random((4,1))

# Set Layer 0 as the Input data
layer_0 = X

# Set the Epochs
epochs = 50000

for iter in range(epochs):
    # Feed Forward through 3 Layers (Layer 0 being the I/P Layer)
    layer_1 = nonlin(np.dot(layer_0, weights_l0))                        # Layer 1 --> Activation(Last_Layer(dot)Weights)
    layer_2 = nonlin(np.dot(layer_1, weights_l1))                        # Layer 2 --> Activation(Last_Layer(dot)Weights)
    
    layer_2_error = y - layer_2                                     # Calculate Error - Prediction vs Actual Value
    layer_2_delta = layer_2_error * nonlin(layer_2, True)           # Error Weighted Derivative --> Error * Deriv(Current_Layer)
    
    layer_1_error = np.dot(layer_2_error, weights_l1.T)             # Layer 1 Error = Next Layer's Error (dot) Weights of Current Layer                     
    layer_1_delta = layer_1_error * nonlin(layer_1, True)           # Error Weighted Derivative --> Error * Deriv(Current_Layer)
    
    weights_l1 += np.dot(layer_1.T, layer_2_delta)                  # Update the Weight Vectors
    weights_l0 += np.dot(layer_0.T, layer_1_delta)
    
    if (iter % 10000) == 0:
        print("Error: "+str(np.mean(np.abs(layer_1_error))))        # layer_1_error contains the Error, take the absolute Values and calculate the mean
        print("Accuracy: "+str((1 - np.mean(np.abs(layer_1_error))) * 100))
        print()
        print(layer_2)                                              # These are the Predicted Values

Error: 0.161771457881
Accuracy: 83.8228542119

[[ 0.6796017 ]
 [ 0.73613833]
 [ 0.72636222]
 [ 0.71039858]]
Error: 0.00966021166967
Accuracy: 99.033978833

[[ 0.00354159]
 [ 0.99683551]
 [ 0.99646821]
 [ 0.00314297]]
Error: 0.00729816557787
Accuracy: 99.2701834422

[[ 0.00249795]
 [ 0.99769035]
 [ 0.99749783]
 [ 0.00228305]]
Error: 0.00618318926823
Accuracy: 99.3816810732

[[ 0.00203862]
 [ 0.99808682]
 [ 0.99795556]
 [ 0.00188987]]
Error: 0.00549237677727
Accuracy: 99.4507623223

[[ 0.00176536]
 [ 0.99832872]
 [ 0.9982289 ]
 [ 0.00165108]]
